"""Generated by eval/train_model.py from replays of: requests, flask, httpx, click, rich, attrs. Do not edit."""
BIAS = -6.859047
WEIGHTS = {
    "cc_p": 4.706790,
    "cc_rev_p": 1.582705,
    "log_cc_n": -0.429114,
    "cc_queries": -0.243121,
    "no_cc": -0.042698,
    "rc_p": 1.913402,
    "log_rc_n": 0.318972,
    "import1": -0.214759,
    "import23": -0.566719,
    "imported": 0.355195,
    "log_uses": 0.638900,
    "named_test": 0.703089,
    "tested_by_change": 0.808961,
    "same_dir": -0.160181,
    "path_sim": 1.944391,
    "log_commits": 0.521057,
    "is_test": 0.413876,
    "is_docs": 0.442266,
    "is_other": 1.053603,
}
