"""Generated by eval/train_model.py from replays of: requests, flask, httpx, click, rich, attrs. Do not edit."""
BIAS = -6.563876
WEIGHTS = {
    "cc_p": 4.576841,
    "cc_rev_p": 1.653909,
    "log_cc_n": -0.551019,
    "cc_queries": -0.294594,
    "no_cc": -0.322576,
    "rc_p": 1.918183,
    "log_rc_n": 0.262709,
    "import1": -0.041496,
    "import23": -0.490107,
    "imported": 0.552915,
    "log_uses": 0.678781,
    "named_test": 0.646090,
    "tested_by_change": 0.796740,
    "same_dir": -0.314878,
    "path_sim": 2.068477,
    "log_commits": 0.576123,
    "is_test": 0.495874,
    "is_docs": 0.794977,
    "is_other": 1.075490,
}
